### ISSUE TITLE
Replace deprecated spellchecker library

### ISSUE THREAD

**Issue by SuchitraShankar07** [acmpesuecc/Spell-check#1]
The current spell-checker uses the spellchecker library, which has deprecated dependencies like indexed that do not run on Python 3. 
Replace this library with a different NLP or word-processing library (like TextBlob or LanguageTool.)
Ensure all functions (spell check, synonyms, meanings, origin) are supported with the new library. 
A complete fix will grant you the full 300 points.

**Comment by ShadowMarty** [comment]
Can you please assign this issue to me @SuchitraShankar07

**Comment by DeviousDrops** [comment]
can u assign this issue to me

**Comment by SuchitraShankar07** [comment]
!assign @ShadowMarty 45

**Comment by mebinthattil** [comment]
Can you please assign this issue to me

**Comment by SuchitraShankar07** [comment]
!assign @mebinthattil 45

**Comment by PandaTGOS** [comment]
Hey can I get assigned to this

**Comment by SuchitraShankar07** [comment]
!deassign

**Comment by AdvaySanketi** [comment]
Assign me to this

**Comment by KaparthyReddy** [comment]
Kindly assign.

**Comment by SuchitraShankar07** [comment]
!deassign

**Comment by SuchitraShankar07** [comment]
!assign @AdvaySanketi 20

**Comment by AdvaySanketi** [comment]
!withdraw

**Comment by SavvyHex** [comment]
Can I please work on this?

**Comment by KaparthyReddy** [comment]
Kindly assign.

**Comment by Gunika-Goel** [comment]
Can this be assigned please?

**Comment by SamridhiShreyaa** [comment]
can i be assigned

**Comment by Git-Cat-21** [comment]
can i be assigned to it

**Comment by SuchitraShankar07** [comment]
!assign @SavvyHex

**Comment by SavvyHex** [comment]
Hey, I've actually been assigned another project, so you can go ahead and assign this to someone else, thanks!

**Comment by sherlockhome12** [comment]
hey can i  be assigned this??

**Comment by SuchitraShankar07** [comment]
!assign @sherlockhome12

**Comment by SuchitraShankar07** [comment]
! deassign

**Comment by SuchitraShankar07** [comment]
!deassign

**Comment by AkshayaR11** [comment]
can i get assigned to this?

**Comment by KaparthyReddy** [comment]
could u assign this

**Comment by KaparthyReddy** [comment]
could you assign this

**Comment by laxmanclo** [comment]
Please, assign me this, I would like to please work on this.
