### ISSUE TITLE
History and User Dictionary Persistence

### ISSUE THREAD

**Issue by SuchitraShankar07** [acmpesuecc/Spell-check#2]
Implement persistent storage for user history and custom dictionaries using SQLite.
This ensures that users don't lose their custom-added words or history after closing the application.
Currently it only stores the words in a simple array. 
Ensure your code is dynamic, and can work seamlessly, even if the rest of the project is changed.
Feel free to add required files to the repository.

**Comment by mebinthattil** [comment]
Can you assign this issue to me please 😁

**Comment by SuchitraShankar07** [comment]
!assign @mebinthattil 45

**Comment by SuchitraShankar07** [comment]
!deassign

**Comment by RohanChirbi** [comment]
Can you please assign me to this issue?

**Comment by RohanChirbi** [comment]
@SuchitraShankar07 Sorry to comment a 2nd time, but can you assign me to this issue?

**Comment by KaparthyReddy** [comment]
Kindly assign.

**Comment by mebinthattil** [comment]
Can you please assign this issue to me

**Comment by SuchitraShankar07** [comment]
!assign @mebinthattil 45

**Comment by mebinthattil** [comment]
Can you please extend the time limit

**Comment by Harshaltt** [comment]
can you assign me this please?

**Comment by KaparthyReddy** [comment]
Kindly assign.

**Comment by SuchitraShankar07** [comment]
!deassign

**Comment by SuchitraShankar07** [comment]
!assign @mebinthattil 30

**Comment by Harshaltt** [comment]
can you please assign me this

**Comment by KaparthyReddy** [comment]
Assign

**Comment by SuchitraShankar07** [comment]
!deassign

**Comment by SuchitraShankar07** [comment]
!assign @KaparthyReddy 60

**Comment by Harshaltt** [comment]
assign please

**Comment by mrwhats-it** [comment]
please assign me this issue...

**Comment by SuchitraShankar07** [comment]
!deassign

**Comment by SuchitraShankar07** [comment]
!assign @Harshaltt

**Comment by mrwhats-it** [comment]
could you please assign this issue to me?

**Comment by SuchitraShankar07** [comment]
!assign @Mathew-K-Alexander
