### ISSUE TITLE
UI/UX Overhaul with Dark Mode

### ISSUE THREAD

**Issue by SuchitraShankar07** [acmpesuecc/Spell-check#3]
To elevate the user experience and modernize the application's interface, consider re-writing the program using a more advanced library like libavg, pygame, or pygui.
These libraries offer greater flexibility and performance for creating sleek, modern designs with customizable themes (dark/light modes), fonts, and color schemes, all while delivering a more intuitive and responsive interface. 
This *shift* will allow you to design a more visually appealing UI, enhancing both aesthetics and usability—and who knows, a more polished design could earn you major brownie points!
- make a branch on the main repository titled "remake-(library-of-your-choice)" 
- Rewrite the entire project using library of your choice
- in case the issue mitigating the deprecated library hasn't been solved yet, demonstrate functionality of your remake using some placeholder print statements (if it has been solved, it is expected to be functional in your remake as well)
A well made ui will grant you all the points. Functional, yet basic ui will grant partial points based on result produced.

**Comment by AdvaySanketi** [comment]
can I get assigned to this?

**Comment by SuchitraShankar07** [comment]
!assign @AdvaySanketi 90

**Comment by SuchitraShankar07** [comment]
@AdvaySanketi please contact 6366250274 if you need any assistance regarding the requirements

**Comment by AdvaySanketi** [comment]
@SuchitraShankar07 can you extend by 30 mins

**Comment by SuchitraShankar07** [comment]
!deassign

**Comment by SuchitraShankar07** [comment]
!assign @AdvaySanketi 45

**Comment by SuchitraShankar07** [comment]
This issue has been closed

**Comment by SuchitraShankar07** [comment]
!deassign
