### ISSUE TITLE
Fixing the Banner Display

### ISSUE THREAD

**Issue by SuchitraShankar07** [acmpesuecc/Spell-check#4]
Despite switching modes, only one banner is displayed. Change it so that appropriate banner is displayed everytime the application mode is switched from light to dark and vice-versa.

**Comment by shubhangisrivastava04** [comment]
assign to me pls :)

**Comment by SuchitraShankar07** [comment]
!assign @shubhangisrivastava04

**Comment by mahika34** [comment]
can i be assigned to this?

**Comment by SuchitraShankar07** [comment]
!deassign

**Comment by SuchitraShankar07** [comment]
!assign @shubhangisrivastava04 25

**Comment by satoqibi** [comment]
Hi, can I please be assigned this

**Comment by chandan365c** [comment]
can i be assigned this

**Comment by RisuKumari11** [comment]
can i get assigned this

**Comment by SuchitraShankar07** [comment]
Sorry guys, this issue has been resolved and is now closed. Try for other issues

**Comment by bwaklog** [comment]
!deassign
