### ISSUE TITLE
Real-Time Pronunciation with Phonetic Suggestions

### ISSUE THREAD

**Issue by SuchitraShankar07** [acmpesuecc/Spell-check#5]
Enhance the pronunciation feature by offering phonetic suggestions for tricky words. 
Use a library that gives IPA (International Phonetic Alphabet) transcriptions and integrates them into the UI for the user to read while hearing the pronunciation. (or fetch an api from a relevant website for the same, your wish :D)

**Comment by Son-0f-Anton** [comment]
Can I be assigned this issue?

**Comment by ManishMDharani** [comment]
can i be assigned this issue?

**Comment by SuchitraShankar07** [comment]
!assign @Anagha-Rao-53 35

**Comment by SuchitraShankar07** [comment]
!deassign

**Comment by Son-0f-Anton** [comment]
Hello, had gone for dinner. Can I be reassigned?

**Comment by Anagha-Rao-53** [comment]
Er, the folks here said I have to message again

**Comment by mrwhats-it** [comment]
could i be assigned this issue?

**Comment by Ferrari2025** [comment]
can you please assign me to this issue?

**Comment by Son-0f-Anton** [comment]
!withdraw

**Comment by SuchitraShankar07** [comment]
!deassign

**Comment by SuchitraShankar07** [comment]
!assign @Anagha-Rao-53 35

**Comment by mrwhats-it** [comment]
could you please assign the issue to me?

**Comment by SuchitraShankar07** [comment]
!assign @Mathew-K-Alexander 35

**Comment by SuchitraShankar07** [comment]
@Anagha-Rao-53 hope you are okay to work on this, kindly lmk if you aren't

**Comment by SuchitraShankar07** [comment]
@Mathew-K-Alexander will assign to you, at second priority

**Comment by Son-0f-Anton** [comment]
working on something else right now :)

**Comment by mrwhats-it** [comment]
could you please assign the issue to me?

**Comment by codebuddyjr** [comment]
assign

**Comment by mrwhats-it** [comment]
please assign the issue... I have asked muliple times in last 2hrs...

**Comment by SuchitraShankar07** [comment]
!deassign

**Comment by SuchitraShankar07** [comment]
!assign @Mathew-K-Alexander 40

**Comment by SuchitraShankar07** [comment]
@Mathew-K-Alexander please us ui.py for any work

**Comment by Mathew-K-Alexander** [comment]
would you like me to add the changes to the pronounce button? i think its non functional

**Comment by Gekkouga77** [comment]
hey could i pls be assigned to this if possible? @SuchitraShankar07

**Comment by SuchitraShankar07** [comment]
@Mathew-K-Alexander are you still working on this?

**Comment by SuchitraShankar07** [comment]
!deassign

**Comment by SuchitraShankar07** [comment]
!assign @Mathew-K-Alexander

**Comment by SuchitraShankar07** [comment]
@Mathew-K-Alexander hey are you working on this

**Comment by SuchitraShankar07** [comment]
!deassign

**Comment by SuchitraShankar07** [comment]
This issue has been resolved
