### ISSUE TITLE
Add Multi-Language Spell Check Support

### ISSUE THREAD

**Issue by SuchitraShankar07** [acmpesuecc/Spell-check#6]
Expand the spell-checking feature to support multiple languages (e.g., Spanish, French, etc.). This would involve adding additional language datasets and ensuring seamless switching between languages without affecting the current functionality.
Feel free to use any library/api/dataset of your choice ( as long as it doesn't make the rest of the application too laggy)
Knowledge of the languages implemented is not required :)

**Comment by IngaleChinmay04** [comment]
I would like to take on this task. Could you please assign it to me?

**Comment by GSuryaP** [comment]
could you please assign me this issue?

**Comment by SuchitraShankar07** [comment]
!assign @GSuryaP 35

**Comment by Gunika-Goel** [comment]
can i be assigned to this please?

**Comment by SuchitraShankar07** [comment]
!extend 25

**Comment by SuchitraShankar07** [comment]
!assign @GSuryaP 25

**Comment by SuchitraShankar07** [comment]
!deassign

**Comment by SuchitraShankar07** [comment]
!assign @GSuryaP 25

**Comment by GSuryaP** [comment]
I'm done with my dinner.

**Comment by SuchitraShankar07** [comment]
!deassign

**Comment by SuchitraShankar07** [comment]
!assign @GSuryaP 10

**Comment by SuchitraShankar07** [comment]
!deassign

**Comment by SuchitraShankar07** [comment]
!assign @GSuryaP 10

**Comment by SuchitraShankar07** [comment]
please make a pull request

**Comment by mahika34** [comment]
can i be assigned

**Comment by SuchitraShankar07** [comment]
!deassign

**Comment by SuchitraShankar07** [comment]
!assign @GSuryaP 10

**Comment by SuchitraShankar07** [comment]
!assign @GSuryaP

**Comment by SuchitraShankar07** [comment]
This issue has been resolved.

**Comment by GSuryaP** [comment]
!withdraw
