### ISSUE TITLE
Vocab Builder with flashcards

### ISSUE THREAD

**Issue by SuchitraShankar07** [acmpesuecc/Spell-check#7]
Develop an interactive vocabulary builder that transforms the way users learn new words. When users look up a word, they can choose to create a digital flashcard for that word, which will include its meaning, synonyms, and an example sentence. Users can later review these flashcards, quiz themselves, and track their learning progress.
Suggested features:
- Flashcard Creation: After retrieving a word's meaning, synonyms, and examples, users can easily **create** a flashcard with this information. (subsequently, **delete** flashcards as well)
- Review Mode: Users can access a dedicated section to **review** their flashcards, with options to shuffle, repeat, or quiz themselves on the vocabulary.
- Progress Tracking: Implement a simple tracking mechanism that shows how many words the user has learned and their accuracy in quizzes, **updates** with every flashcard that is viewed/made (doesn't have to be too complicated)

- Visual Enhancements: Consider adding images or icons related to the words to make the flashcards more engaging.

> Note: "User" doesn't mean adding code to identify multiple users by login, (although that as a self-identified issue would definitely fetch points), the initial use case is one user, so maintain one set of progress logs :)

Feel free to use any other library for the same, ensure your final submission is integrated with the rest of the application.

**Comment by Am3li1** [comment]
I would like to work on this issue. Could you please assign it to me?

**Comment by SuchitraShankar07** [comment]
!assign @Am3li1 75

**Comment by Am3li1** [comment]
i am going for dinner. Please pause the time

**Comment by SuchitraShankar07** [comment]
will not be able to pause the time, can extend it for 30 minutes more :+1:

**Comment by SuchitraShankar07** [comment]
!extend 30

**Comment by Am3li1** [comment]
am i unassigned?

**Comment by namrataaravinda** [comment]
can i get this assigned please?

**Comment by bwaklog** [comment]
!deassign

**Comment by bwaklog** [comment]
@Am3li1 please **do not** manually deassign yourself from an issue. Use `!withdraw` if you feel like you dont want to contribute to the issue anymore.

**Comment by SuchitraShankar07** [comment]
!assign @namrataaravinda  35

**Comment by KaparthyReddy** [comment]
Kindly assign.

**Comment by namrataaravinda** [comment]
can you extend the time ?

**Comment by SuchitraShankar07** [comment]
!assign @namrataaravinda 45

**Comment by SuchitraShankar07** [comment]
!deassign

**Comment by SuchitraShankar07** [comment]
@namrataaravinda you're already assigned to a different repository, kindly check on that.

**Comment by AkshathaAcharya55555** [comment]
could you assign this to me...

**Comment by KaparthyReddy** [comment]
Kindly assign.

**Comment by namrataaravinda** [comment]
I already started with this. Could you please recheck and  re-assign?

**Comment by shubhangisrivastava04** [comment]
could you assign

**Comment by SuchitraShankar07** [comment]
!assign @shubhangisrivastava04 60

**Comment by SuchitraShankar07** [comment]
!assign @shubhangisrivastava04 60

**Comment by SuchitraShankar07** [comment]
!assign @shubhangisrivastava04 60

**Comment by SuchitraShankar07** [comment]
!deassign

**Comment by sherlockhome12** [comment]
hey can i get this assigned??

**Comment by sherlockhome12** [comment]
@SuchitraShankar07

**Comment by SuchitraShankar07** [comment]
!assign @sherlockhome12

**Comment by sherlockhome12** [comment]
hey pls deassign and check the pr once

**Comment by KaparthyReddy** [comment]
could u assign this?

**Comment by SuchitraShankar07** [comment]
!deassign

**Comment by SuchitraShankar07** [comment]
!assign @KaparthyReddy

**Comment by Roshr2211** [comment]
Please do assign

**Comment by SuchitraShankar07** [comment]
This issue has been resolved
